# Load: Configurations
source $HOME/.zsh/config

# Load: Plugins
source $HOME/.zsh/plugins

# Load: OH-MY-ZSH
source $ZSH/oh-my-zsh.sh

# Load: ALIASES
source $HOME/.zsh/aliases

# Load: FUNCTIONS
source $HOME/.zsh/functions

# Load: PATH updates
source $HOME/.zsh/path_updates
